"""mixins

Revision ID: 4ab8bc0aebf1
Revises: d5805c7a04ec
Create Date: 2025-11-07 13:13:26.738992

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ab8bc0aebf1"
down_revision: Union[str, Sequence[str], None] = "d5805c7a04ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_branches",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "company_branches",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_company_branches_created_at"),
        "company_branches",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_branches_updated_at"),
        "company_branches",
        ["updated_at"],
        unique=False,
    )
    op.add_column(
        "qr_codes",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "qr_codes",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_qr_codes_created_at"), "qr_codes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_qr_codes_updated_at"), "qr_codes", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qr_codes_updated_at"), table_name="qr_codes")
    op.drop_index(op.f("ix_qr_codes_created_at"), table_name="qr_codes")
    op.drop_column("qr_codes", "updated_at")
    op.drop_column("qr_codes", "created_at")
    op.drop_index(op.f("ix_company_branches_updated_at"), table_name="company_branches")
    op.drop_index(op.f("ix_company_branches_created_at"), table_name="company_branches")
    op.drop_column("company_branches", "updated_at")
    op.drop_column("company_branches", "created_at")
    # ### end Alembic commands ###
