"""rename model name

Revision ID: d5805c7a04ec
Revises: 35620debf9a6
Create Date: 2025-11-07 10:26:20.037589

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5805c7a04ec"
down_revision: Union[str, Sequence[str], None] = "35620debf9a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qr_codes_company_branch_id"), table_name="qr_codes")
    op.create_index(
        op.f("ix_qr_codes_company_branch_id"),
        "qr_codes",
        ["company_branch_id"],
        unique=True,
    )
    op.create_unique_constraint(
        "uq_qr_codes_company_branch_id", "qr_codes", ["company_branch_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_qr_codes_company_branch_id", "qr_codes", type_="unique")
    op.drop_index(op.f("ix_qr_codes_company_branch_id"), table_name="qr_codes")
    op.create_index(
        op.f("ix_qr_codes_company_branch_id"),
        "qr_codes",
        ["company_branch_id"],
        unique=False,
    )
    # ### end Alembic commands ###
